"""
Trade Idea Generator Page

Shows signal-driven trade ideas in two sections:
  1. RV Bond Pairs  — top cross-country pair trades based on correlation,
                      spread differential z-score, and OLS hedge ratio.
  2. All Ideas      — full shortlist: single-bond RV, curve, and macro ideas.

Every idea is backed by computed analytics, not generic text.
"""

from __future__ import annotations

import pandas as pd
import streamlit as st

from config.settings import COLORS
from config.theme import STREAMLIT_CSS
from src.data.session import get_app_data
from src.analytics.trade_ideas import ideas_to_dataframe
from pages.overview import _confidence_badge


# ── Z-score colour helper ─────────────────────────────────────────────────────

def _zscore_color(z: float) -> str:
    if abs(z) >= 2.5:
        return COLORS["negative"]
    if abs(z) >= 2.0:
        return COLORS["warning"]
    return COLORS["primary"]


def _zscore_badge(z: float) -> str:
    color = _zscore_color(z)
    sign  = "+" if z > 0 else ""
    label = "STRONG" if abs(z) >= 2.5 else "SIGNAL"
    return (
        f"<span style='background:{color};color:#fff;padding:2px 8px;"
        f"border-radius:4px;font-size:11px;font-weight:700'>"
        f"{label} Z={sign}{z:.1f}σ</span>"
    )


# ═════════════════════════════════════════════════════════════════════════════
# Page entry point
# ═════════════════════════════════════════════════════════════════════════════

def render() -> None:
    st.markdown(STREAMLIT_CSS, unsafe_allow_html=True)
    st.title("Trade Idea Generator")
    st.caption(
        "Signal-driven trade ideas generated by combining RV screener z-scores, "
        "curve trade opportunities, and macro factor beta analysis."
    )

    data        = get_app_data()
    rv_pairs    = data.get("rv_pairs", [])
    trade_ideas = data["trade_ideas"]

    tab_pairs, tab_ideas = st.tabs(["RV Bond Pairs", "All Trade Ideas"])

    # ══════════════════════════════════════════════════════════════════════════
    # Tab 1 — RV Bond Pairs
    # ══════════════════════════════════════════════════════════════════════════
    with tab_pairs:
        _render_rv_pairs(rv_pairs)

    # ══════════════════════════════════════════════════════════════════════════
    # Tab 2 — All Trade Ideas  (Curve + RV from analytics + RV pairs)
    # ══════════════════════════════════════════════════════════════════════════
    with tab_ideas:
        _render_all_ideas(trade_ideas, rv_pairs)


# ═════════════════════════════════════════════════════════════════════════════
# Tab 1: RV Bond Pairs
# ═════════════════════════════════════════════════════════════════════════════

def _render_rv_pairs(pairs: list[dict]) -> None:
    st.subheader("Top RV Bond Pairs")
    st.caption(
        "Cross-country pairs screened on correlation, 126-day spread differential "
        "z-score, and OLS hedge ratio. Only pairs with corr ≥ 0.55 and |z| ≥ 1.5σ "
        "generate a signal. Same-country and 30Y bonds excluded."
    )

    if not pairs:
        st.info(
            "No RV pair signals at current thresholds. "
            "This is normal when cross-country spread differentials are near "
            "their historical averages."
        )
        return

    # KPI bar
    k1, k2, k3, k4 = st.columns(4)
    k1.metric("Pairs Found", len(pairs))
    k2.metric("Avg Correlation", f"{sum(p['correlation'] for p in pairs) / len(pairs):.2f}")
    k3.metric("Avg |Z-Score|",   f"{sum(abs(p['zscore']) for p in pairs) / len(pairs):.1f}σ")
    k4.metric("Strong (|Z|≥2.5)", sum(1 for p in pairs if abs(p["zscore"]) >= 2.5))

    st.divider()

    for rank, pair in enumerate(pairs, 1):
        _render_pair_card(rank, pair)


def _render_pair_card(rank: int, p: dict) -> None:
    z          = p["zscore"]
    corr       = p["correlation"]
    dislo      = p["dislocation_bps"]
    cur_diff   = p["current_diff_bps"]
    avg_diff   = p["hist_avg_diff_bps"]
    hedge_r    = p["hedge_ratio"]
    dv01_r     = p["dv01_ratio"]
    long_id    = p["long_id"]
    short_id   = p["short_id"]
    why        = p["why"]

    mat_label  = (
        f"{p['maturity_a']}Y" if p["maturity_a"] == p["maturity_b"]
        else f"{p['maturity_a']}Y vs {p['maturity_b']}Y"
    )
    header = (
        f"#{rank} — {p['id_a']} / {p['id_b']}  "
        f"({p['country_a']} vs {p['country_b']}, {mat_label})"
    )

    with st.expander(header, expanded=(rank <= 3)):
        # ── Top bar: badge + ratings ──────────────────────────────────────────
        col_title, col_badge = st.columns([3, 1])
        with col_title:
            st.markdown(
                f"<h4 style='color:{COLORS['text']};margin:0'>"
                f"{p['id_a']} / {p['id_b']}</h4>"
                f"<span style='color:{COLORS['text_muted']};font-size:12px'>"
                f"{p['country_a']} {p['rating_a']} "
                f"vs {p['country_b']} {p['rating_b']}"
                f"</span>",
                unsafe_allow_html=True,
            )
        with col_badge:
            st.markdown(_zscore_badge(z), unsafe_allow_html=True)

        st.markdown("<br>", unsafe_allow_html=True)

        # ── Metric row ────────────────────────────────────────────────────────
        m1, m2, m3, m4 = st.columns(4)
        m1.metric("Correlation",      f"{corr:.2f}")
        m2.metric("Spread Diff",      f"{cur_diff:+.0f} bps",
                  delta=f"{dislo:+.0f} bps vs avg", delta_color="inverse")
        m3.metric("Historical Avg",   f"{avg_diff:+.0f} bps")
        m4.metric("Z-Score",          f"{z:+.2f}σ")

        st.markdown("<br>", unsafe_allow_html=True)

        # ── Trade box ─────────────────────────────────────────────────────────
        dv01_text = (
            f"&nbsp;&nbsp;|&nbsp;&nbsp;DV01 ratio: <b>{dv01_r:.2f}x</b>"
            if dv01_r is not None else ""
        )
        st.markdown(
            f"""
<div style="background:{COLORS['surface2']};border-left:4px solid {_zscore_color(z)};
     padding:12px 16px;border-radius:6px;margin-bottom:8px;">
  <span style="color:{COLORS['text']};font-size:15px;font-weight:700">
    {p['trade']}
  </span><br>
  <span style="color:{COLORS['text_muted']};font-size:12px">
    OLS Hedge Ratio: <b style="color:{COLORS['text']}">{hedge_r:.2f}x</b>
    {dv01_text}
  </span>
</div>
""",
            unsafe_allow_html=True,
        )

        # ── Rationale ─────────────────────────────────────────────────────────
        st.markdown(
            f"<p style='color:{COLORS['text_muted']};font-size:13px'>{why}</p>",
            unsafe_allow_html=True,
        )

        # ── Guidance note ─────────────────────────────────────────────────────
        st.caption(
            f"Hedge ratio {hedge_r:.2f}x computed via OLS regression of "
            f"Δ(OAS {long_id}) on Δ(OAS {short_id}) over the full sample. "
            "Z-score based on 126-day rolling history of the spread differential. "
            "Signal requires both legs to be liquid."
        )


# ═════════════════════════════════════════════════════════════════════════════
# Tab 2: All Trade Ideas
# ═════════════════════════════════════════════════════════════════════════════

def _render_all_ideas(trade_ideas: list[dict], rv_pairs: list[dict] | None = None) -> None:
    # Convert rv_pairs → trade_idea dicts and merge in
    rv_pair_ideas = _rv_pairs_to_ideas(rv_pairs or [])
    combined = trade_ideas + rv_pair_ideas

    if not combined:
        st.warning(
            "No trade ideas generated. This may occur if the dataset is too short "
            "for meaningful z-scores. Try reloading data."
        )
        return

    # Re-rank after merge
    combined = sorted(combined, key=lambda x: x.get("confidence_score", 0), reverse=True)
    for i, idea in enumerate(combined, 1):
        idea["rank"] = i

    # ── Sidebar filters ────────────────────────────────────────────────────────
    st.sidebar.markdown("### Idea Filters")

    all_types     = sorted({i["trade_type"]          for i in combined})
    all_countries = sorted({i.get("country", "")     for i in combined})

    sel_types     = st.sidebar.multiselect("Trade Types",  all_types,     default=all_types)
    sel_countries = st.sidebar.multiselect("Countries",    all_countries, default=all_countries)
    min_conf      = st.sidebar.slider(
        "Min Confidence", 0.0, 1.0, 0.0, 0.05, format="%.0f%%",
    )

    filtered = [
        i for i in combined
        if i["trade_type"]        in sel_types
        and i.get("country", "") in sel_countries
        and i["confidence_score"] >= min_conf
    ]

    # ── KPI row ────────────────────────────────────────────────────────────────
    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Total Ideas",    len(filtered))
    c2.metric("RV Ideas",       sum(1 for i in filtered if "Relative Value" in i["trade_type"]))
    c3.metric("Curve Ideas",    sum(1 for i in filtered if "Curve"          in i["trade_type"]))
    c4.metric("High Conf ≥70%", sum(1 for i in filtered if i["confidence_score"] >= 0.70))

    st.divider()

    view = st.radio(
        "Display Mode", ["Cards", "Table"],
        horizontal=True, label_visibility="collapsed",
    )

    if view == "Table":
        _render_table_view(filtered)
    else:
        _render_card_view(filtered)


def _rv_pairs_to_ideas(pairs: list[dict]) -> list[dict]:
    """Convert rv_pairs screener output to the trade_ideas dict format."""
    ideas = []
    for p in pairs:
        z    = p.get("zscore", 0)
        corr = p.get("correlation", 0)
        # Confidence: combination of |z| and correlation
        conf = min(1.0, (abs(z) / 3.0) * 0.6 + corr * 0.4)
        ideas.append({
            "rank":             0,  # will be reassigned
            "title":            p.get("trade", f"{p.get('id_a')} / {p.get('id_b')}"),
            "trade_type":       "Relative Value",
            "direction":        "Long" if z > 0 else "Short",
            "country":          f"{p.get('country_a', '')} / {p.get('country_b', '')}",
            "rationale":        p.get("why", ""),
            "confidence_score": round(conf, 3),
            "supporting_metrics": {
                "Correlation":    f"{corr:.2f}",
                "Z-Score":        f"{z:+.2f}σ",
                "Spread Diff":    f"{p.get('current_diff_bps', 0):+.0f} bps",
                "Hist Avg":       f"{p.get('hist_avg_diff_bps', 0):+.0f} bps",
                "Hedge Ratio":    f"{p.get('hedge_ratio', 1.0):.2f}x",
            },
            "hedge_suggestion": (
                f"{p.get('trade', 'See pair')} — Hedge ratio {p.get('hedge_ratio', 1.0):.2f}x"
            ),
            "catalyst_notes":   "Signal based on spread differential z-score vs 126-day history.",
            "key_risks":        [
                "Spread differential may reflect structural differences rather than dislocation.",
                "Correlation may not hold in stressed markets.",
            ],
        })
    return ideas


# ═════════════════════════════════════════════════════════════════════════════
# Render helpers — cards / table
# ═════════════════════════════════════════════════════════════════════════════

def _render_card_view(ideas: list[dict]) -> None:
    for idea in ideas:
        conf       = idea["confidence_score"]
        direction  = idea.get("direction", "")
        trade_type = idea["trade_type"]

        border_colour = {
            "Long":      COLORS["positive"],
            "Short":     COLORS["negative"],
            "steepener": COLORS["warning"],
            "flattener": COLORS["warning"],
        }.get(direction, COLORS["primary"])

        with st.expander(
            f"#{idea['rank']} — {idea['title']}  |  {trade_type}",
            expanded=idea["rank"] <= 3,
        ):
            col_title, col_badge = st.columns([3, 1])
            with col_title:
                st.markdown(
                    f"<h4 style='color:{COLORS['text']}'>{idea['title']}</h4>",
                    unsafe_allow_html=True,
                )
                st.markdown(
                    f"<span style='color:{COLORS['text_muted']};font-size:12px'>"
                    f"Type: **{trade_type}** | Direction: **{direction}** | "
                    f"Country: **{idea.get('country','N/A')}**</span>",
                    unsafe_allow_html=True,
                )
            with col_badge:
                st.markdown(_confidence_badge(conf), unsafe_allow_html=True)

            st.divider()

            col_rat, col_met = st.columns([2, 1])
            with col_rat:
                st.markdown("**Rationale**")
                st.markdown(
                    f"<p style='color:{COLORS['text']};font-size:13px'>{idea['rationale']}</p>",
                    unsafe_allow_html=True,
                )
                st.markdown("**Hedge Suggestion**")
                st.info(idea.get("hedge_suggestion", "N/A"))
                st.markdown("**Catalyst Notes**")
                st.caption(idea.get("catalyst_notes", "N/A"))

            with col_met:
                st.markdown("**Supporting Metrics**")
                for k, v in idea.get("supporting_metrics", {}).items():
                    _mini_metric(k, v)
                st.markdown("**Key Risks**")
                for risk in idea.get("key_risks", []):
                    st.markdown(
                        f"<p style='color:{COLORS['negative']};font-size:11px'>⚠ {risk}</p>",
                        unsafe_allow_html=True,
                    )


def _render_table_view(ideas: list[dict]) -> None:
    ideas_df = ideas_to_dataframe(ideas)
    st.dataframe(ideas_df, use_container_width=True, height=500)
    csv = ideas_df.to_csv(index=False).encode("utf-8")
    st.download_button("Download Ideas CSV", csv, "trade_ideas.csv", "text/csv")


def _mini_metric(label: str, value: str) -> None:
    st.markdown(
        f"""
<div style="display:flex;justify-content:space-between;
     border-bottom:1px solid {COLORS['surface2']};padding:3px 0;
     font-size:12px;">
  <span style="color:{COLORS['text_muted']}">{label}</span>
  <span style="color:{COLORS['text']};font-weight:600">{value}</span>
</div>
""",
        unsafe_allow_html=True,
    )
